/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vaadin_jonatan_nativefsevents_NativeFSEvents */

#ifndef _Included_org_vaadin_jonatan_nativefsevents_NativeFSEvents
#define _Included_org_vaadin_jonatan_nativefsevents_NativeFSEvents
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_vaadin_jonatan_nativefsevents_NativeFSEvents
 * Method:    monitor
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT void JNICALL Java_org_vaadin_jonatan_nativefsevents_NativeFSEvents_monitor
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_vaadin_jonatan_nativefsevents_NativeFSEvents
 * Method:    unmonitor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_vaadin_jonatan_nativefsevents_NativeFSEvents_unmonitor
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
